<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('voucher_users', function (Blueprint $table) {
            $table->uuid('id')->primary();

            $table->string('name');

            // Discount percentage this code gives when redeemed.
            $table->decimal('percentase', 5, 2)->default(0);

            // 6-digit code, always unique. Auto-generated by
            // App\Models\VoucherUser if left empty on create.
            $table->string('kode_voucher', 6)->unique();

            // Total quota: how many times this code can be redeemed
            // across ALL users combined.
            $table->unsignedInteger('limit');

            // How many times a single user may redeem this same code
            // (e.g. 1 = one redemption per user, even if `limit` above
            // still has quota left).
            $table->unsignedInteger('use_by_user')->default(1);

            $table->date('valid_from');
            $table->date('valid_until');

            // active | expire | used | inactive — superadmin sets this
            // manually; there's no background job auto-flipping it based
            // on valid_until/limit, by design (kept as a plain CRUD field
            // per the request, not a computed usage-tracking system).
            $table->string('status', 20)->default('active');

            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('voucher_users');
    }
};
